apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    gcb-build-id: f653bfa8-0158-45aa-a76a-e58834468906
    gcb-trigger-id: d3998691-b7ad-4f62-880b-209673e0bcc7
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"gcb-build-id":"f653bfa8-0158-45aa-a76a-e58834468906","gcb-trigger-id":"d3998691-b7ad-4f62-880b-209673e0bcc7"},"labels":{"app":"reggeltbot","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"reggeltbot","app.kubernetes.io/version":"176ebb0383a61224964a96a0cec4e1838f8c4a9e"},"name":"reggeltbot","namespace":"default"},"spec":{"progressDeadlineSeconds":10000,"replicas":1,"selector":{"matchLabels":{"app":"reggeltbot"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"gcb-build-id":"f653bfa8-0158-45aa-a76a-e58834468906","gcb-trigger-id":"d3998691-b7ad-4f62-880b-209673e0bcc7"},"labels":{"app":"reggeltbot","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"reggeltbot","app.kubernetes.io/version":"176ebb0383a61224964a96a0cec4e1838f8c4a9e"}},"spec":{"containers":[{"image":"gcr.io/zal1000/github.com/zal1000/reggeltbot@sha256:7e8d1eae626e51c243d620f3c0ca15685189929b6c3be5b00f888884fa69c7e8","imagePullPolicy":"IfNotPresent","name":"reggeltbot-1"}]}}}}
  creationTimestamp: "2020-11-19T23:48:46Z"
  generation: 10
  labels:
    app: reggeltbot
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: reggeltbot
    app.kubernetes.io/version: 176ebb0383a61224964a96a0cec4e1838f8c4a9e
  name: reggeltbot
  namespace: default
  resourceVersion: "11072"
  selfLink: /apis/apps/v1/namespaces/default/deployments/reggeltbot
  uid: 42a0c07f-8c3b-4c36-9c64-0822c98df212
spec:
  progressDeadlineSeconds: 10000
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reggeltbot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gcb-build-id: f653bfa8-0158-45aa-a76a-e58834468906
        gcb-trigger-id: d3998691-b7ad-4f62-880b-209673e0bcc7
      creationTimestamp: null
      labels:
        app: reggeltbot
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: reggeltbot
        app.kubernetes.io/version: 176ebb0383a61224964a96a0cec4e1838f8c4a9e
    spec:
      containers:
      - image: gcr.io/zal1000/github.com/zal1000/reggeltbot@sha256:7e8d1eae626e51c243d620f3c0ca15685189929b6c3be5b00f888884fa69c7e8
        imagePullPolicy: IfNotPresent
        name: reggeltbot-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
